# API代理配置文件
# 自动生成

# 端口801的API代理
server {
    listen       801;
    server_name  localhost;

    access_log  logs/api_801_access.log;
    error_log   logs/api_801_error.log;

    location /api/ {
        # proxy_pass http://localhost:8081; #R 新地址
        # proxy_pass http://localhost:8080; #R 新地址
        proxy_pass http://localhost:8082; #R 新地址
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

